### ISSUE TITLE
Pharmacies in Retail Grocery

### ISSUE THREAD

**Issue by davidweinfeld** [openooh/venue-taxonomy#127]
It's not clear whether a screen in the pharmacy section of a Retail_Grocery or Retail_Big Box should be listed as Retail_Pharmacy or it's true parent venue type. 

Could we create a grandchild to the Retail_Grocery venue type for the pharmacy section of the store? So, the taxonomy could like like Retail_Grocery_Pharmacy.

**Comment by jayshao** [comment]
To be honest - I don't believe we want this kind of repetition in the taxonomy. In this case, I would suggest that we probably want to maintain the current format, and ask for the "most specific" view, since I think in most cases either what we have will be a pharmacy chain/publisher where a few of their locations happen to be embedded, or a Big-Box retailer where a few of their screens happen to be a pharmacy.

I do think we could explore whether we either want to:

1) Allow multiple selections for taxonomy (I suspect this is likely to create confusion and not necessarily to pubs interests, since blocking is a common reason for types)
2) Perhaps maintain the taxonomy, but introduce a concept (either as part of this spec, or perhaps just directly in OpenRTB or wire protocols for "related categories" or "nearby POI" or something like that

@davidweinfeld would something like the proposal above address your use cases?

**Comment by davidweinfeld** [comment]
While it's a thoughtful approach, I don't think the proposal above addresses our use cases. Nor do think that it effectively supports the most accurate level of venue identification. 

We have two networks that have thousands of screens in the pharmacy sections of grocery and big box retail stores. Today, the pharmacy venue type sees less than 0.2% of all demand on one of programmatic DOOH's largest exchanges. Grocery stores, on the other hand, see in excess of 5% of all demand. Some of the reasons for this include a higher number of product SKUs, higher consumer spend, longer dwell times, and, most definitely, higher venue traffic in grocery stores.

As such, there's a lot of demand impact when reclassifying a venue type. With that in mind, I think the section of a retail store is preferential (Retail Grocery.Aisle.Pharmacy) and much more accurate than calling it Retail.Pharmacy. This is based on the profile of the audience, buyer behavior, and advertiser expectations of the primary venue type.

**Comment by jayshao** [comment]
Based on discussion with expert group - this will not be added to the taxonomy in 1.2 - recommend we consider fleshing out some of the cases more thoroughly.

e.g. I think the argument around current spend patterns is a difficult one - the taxonomy should be focused on accurately describing the activities and behaviors happening at a location - and the market should determine it's valuation of different areas.

In the interim, for in-grocery pharmacy sections, I think it would be reasonable to consider (working with any partners you're working with) categorizing them as grocery stores - since if there are multiple potential classifications, any/all of them are probably valid - and seeing if in a future revision of the spec or related specs we might want to consider something more prescriptive

**Comment by jayshao** [comment]
marking as closed for 1.2 - but open to creating a separate followup to explore in more detail
